cportal/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('register/', views.register, name='register'),
    path('add/', views.add_company, name='add_company'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('<int:id>/', views.companydetail, name='detail'),

    # Add more paths as needed
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecomm/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    #path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path('company/', include("cportal.urls")),
    path("__debug__/", include("debug_toolbar.urls")),

]

cportal/models.py
from django.db import models
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField

class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'Country'
        verbose_name_plural = 'Countries'

class State(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Company(models.Model):
    company_status_choices= {
    "ACT": "ACTIVE",
    "DRM": "DORMANT",
    "INAC": "INACTIVE",
    "DRFT": "DRAFT"
    }

    company_types = {
        'PVT': 'Private Limited',
        'LTD': 'Public Limited',
        'SLP': 'Sole Proprietorship',
        'None': 'Unknown'
    }
    name = models.CharField(max_length=200)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, default = 5, on_delete=models.CASCADE, verbose_name='Owner')
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, verbose_name='Country')
    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True, verbose_name='State')
    cin = models.CharField(max_length=30, default=None, null=True, verbose_name='CIN')
    status = models.CharField(max_length=15, choices=company_status_choices, default='DRAFT', verbose_name='Status')
    address = models.CharField(max_length=40, default=None, null=True, verbose_name='Address')
    zip = models.CharField(max_length=6, default=None, null=True, blank=True, verbose_name='Zip Code')
    type = models.CharField(max_length=4, choices=company_types, default=company_types["None"], verbose_name='Company Type')
    tan = models.CharField(max_length=30, default=None, null=True, blank=True, verbose_name='TAN #')
    pan = models.CharField(max_length=10, default=None, null=True, blank=True, verbose_name= 'PAN #')
    gstin = models.CharField(max_length=20, default=None, null=True, blank=True, verbose_name= 'GSTIN')
    email = models.EmailField(max_length=254, null=True, default=None, blank=True, verbose_name= 'Company Email')
    phone = PhoneNumberField(null=True, blank=True, unique=True, name="Phone Number")
    
    # add more fields as per your requirements

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'Company'
        verbose_name_plural = 'Companies'


class Director(models.Model):
    dir_status_choices= {
    "ACT": "ACTIVE",
    "INAC": "INACTIVE",
    "DRFT": "DRAFT"
    }
    name = models.CharField(max_length=200)
    #owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, verbose_name='Country')
    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True, verbose_name='State')
    din = models.CharField(max_length=30, default=None, null=True, blank=True, verbose_name='DIN #')
    status = models.CharField(max_length=15, choices=dir_status_choices, default='DRAFT', verbose_name='Status')
    address = models.CharField(max_length=40, default=None, null=True, blank=True, verbose_name='Address')
    zip = models.CharField(max_length=6, default=None, null=True, blank=True, verbose_name='Zip Code')
    # add more fields as per your requirements
    pan = models.CharField(max_length=10, default=None, null=True, blank=True, verbose_name='PAN #')
    company = models.ManyToManyField(Company, through='CompanyDirector', verbose_name='Linked Companies')#on_delete=models.SET_NULL, null=True)
    email = models.EmailField(max_length=254, null=True, default=None, blank=True, verbose_name='Email')
    phone = PhoneNumberField(null=True, blank=True, unique=True, name="Phone Number")

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'Director'
        verbose_name_plural = 'Directors'

class CompanyDirector(models.Model):

    company = models.ForeignKey(Company, on_delete=models.SET_NULL, null=True, verbose_name='Company')
    director = models.ForeignKey(Director, on_delete=models.SET_NULL, null=True, verbose_name='Director')
    class Meta:
        verbose_name = 'Associated with'
        verbose_name_plural = 'Associated with'



class OrderType(models.Model):
    def get_currencies():
        return {i: i for i in settings.CURRENCIES}
    type = models.CharField(max_length=200, verbose_name='Order Type')
    description = models.TextField(verbose_name='Description', help_text='Enter a brief description of the Order Type')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField(max_length=3, choices=get_currencies)

    def __str__(self):
        return self.type

class Order(models.Model):
    order_status_choices = {
    "COMPLETED": "COMPLETED",
    "RENEWED": "RENEWED",
    "CANCELLED": "CANCELLED",
    "RECEIVED": "RECEIVED"

    }

    company = models.ForeignKey(Company, on_delete=models.SET_NULL, null=True, verbose_name='Company')
    status = models.CharField(max_length=15, choices=order_status_choices, default='RECEIVED', verbose_name='Status')
    type = models.ForeignKey(OrderType, on_delete=models.SET_NULL, null=True, default=None, verbose_name='Order Type')
    
    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

cportal/forms.py
from django import forms
from .models import Director, Company

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['name', 'type']

class DirectorForm(forms.ModelForm):
    class Meta:
        model = Director
        fields = ['name', 'email']

cportal/views.py
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from .models import Company, Director
from django.shortcuts import render, get_object_or_404
from .forms import DirectorForm, CompanyForm

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('dashboard')
    else:
        form = UserCreationForm()
    return render(request, 'cportal/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('dashboard')
    else:
        form = AuthenticationForm()
    return render(request, 'cportal/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('login')

def d(request):
    form = AuthenticationForm()
    return render(request, 'cportal/dashboard.html', {'form': form})

@login_required
def dashboard(request):
    comp_ls = Company.objects.filter(owner=request.user)
    return render(request, 'cportal/dashboard.html', {'comp_data': comp_ls})

@login_required
def companydetail(request, id):
    comp = get_object_or_404(Company, pk=id)
    return render(request, 'cportal/detail.html', {'comp': comp})

@login_required
def add_company(request):
    if request.method == 'POST':
        company_form = CompanyForm(request.POST, prefix='company')
        director_form = DirectorForm(request.POST, prefix='director')
        if all([company_form.is_valid(), director_form.is_valid()]):
            company = company_form.save()
            director = director_form.save(commit=False)
            director.save()

            director.company.set([company])   

    else:

        company_form = CompanyForm(prefix='company')
        director_form = DirectorForm(prefix='director')

    return render(request, 'cportal/add_company.html', {'company_form': company_form, 'director_form': director_form})

cportal/templates/cportal/add_company.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <form method="post">
    {% csrf_token %}
    <h2>Company Details</h2>
    {{ company_form.name }}
    {{ company_form.type }}


    <h2>Contact Details</h2>
    {{ director_form.name }}
    <button type="submit">Submit</button>
</form>

  {% endif %}
{% endblock %}

cportal/templates/cportal/dashboard.html
  {% extends "base.html" %}
  {% block content %}
  {% if user.is_authenticated %}
    Hi {{ user.username }}!


      <!-- Card -->
<div class="card">
  <div>
    <div class="card-header">
      <h5 class="card-header-title">Your companies</h5>
    </div>
    <div>
      <a href="{% url 'add_company' %}">Register Company</button>
    </div>
  </div>
    <!-- Table -->
    <div class="table-responsive">
      <table class="table table-borderless table-thead-bordered table-nowrap table-align-middle card-table">
        <thead class="thead-light">
          <tr>
            <th>Company Name</th>
            <th>CIN</th>
            <th>State</th>
            <th>Status</th>
            <th>Directors</th>


          </tr>
        </thead>
  
        <tbody>
        {% for i in comp_data %}

          <tr>
            <td>
              <div class="d-flex align-items-center">
                <div class="flex-shrink-0">
                  <!-- <img class="avatar avatar-sm avatar-circle" src="../assets/img/160x160/img8.jpg" alt="Image Description">
                </div> -->
  
                <div class="flex-grow-1 ms-3">
                  <a class="d-inline-block link-dark" href="#">
                    <h6 class="text-hover-primary mb-0">{{ i }} <!-- <img class="avatar avatar-xss ms-1" src="../assets/svg/illustrations/top-vendor.svg" alt="Image Description" data-bs-toggle="tooltip" data-bs-placement="top" title="Verified user"> -->
                    </h6>
                  </a>
                  <small class="d-block">{{ i.email }}</small>
                </div>
              </div>
            </td>
            <td>
                {{ i.cin }}
            </td>
            <td>
                {{ i.state }}
            </td>
            <td>
                {{ i.status }}
            </td>
            <td>
                <ul>
            {% for ass in i.companydirector_set.all %}
                <li>{{ ass.director.name }}</li>
                {% endfor %}
            </ul>
            </td>
            
          </tr>
    {% endfor %}

        </tbody>
      </table>
    </div>
    <!-- End Table -->
  
  </div>
  <!-- End Card -->
      
{% endif %}
{% endblock %}

cportal/templates/cportal/detail.html
{% extends "base.html" %}
{% block content %}

{% if user.is_authenticated %}


<!-- Page Header -->
<div class="container content-space-1">
  <div class="w-lg-75 mx-lg-auto">
    <div class="page-header">
      <!-- Media -->
      <div class="d-sm-flex mb-3">
        <div class="flex-shrink-0 mb-2 mb-sm-0">
          <a href="../demo-jobs/employer.html">
            <img class="avatar avatar-lg mb-3" src="../assets/svg/brands/capsule-icon.svg" alt="Image Description">
          </a>
        </div>

        <div class="flex-grow-1 ms-sm-4">
          <div class="row">
            <div class="col">
              <h1 class="page-header-title h2">{{ comp.name }}</h1>
            </div>
            <!-- End Col -->

            <div class="col-auto">
              <!-- Checkbbox Bookmark -->
              <div class="form-check form-check-bookmark">
                <input class="form-check-input" type="checkbox" value="" id="jobsPageHeaderBookmarkCheck">
                <label class="form-check-label" for="jobsPageHeaderBookmarkCheck">
                  <span class="form-check-bookmark-default">
                    <i class="bi-star me-1"></i> Save this job
                  </span>
                  <span class="form-check-bookmark-active">
                    <i class="bi-star-fill me-1"></i> Saved
                  </span>
                </label>
              </div>
              <!-- End Checkbbox Bookmark -->
            </div>
            <!-- End Col -->
          </div>
          <!-- End Row -->

          <ul class="list-inline list-separator d-flex align-items-center mb-2">
            <li class="list-inline-item">
              <a class="link" href="../demo-jobs/employer.html">{{ comp.status }}</a>
            </li>
            <li class="list-inline-item">
              <a class="link" href="../demo-jobs/employer.html">{{ comp.email }}</a>
            </li>
          </ul>

          <ul class="list-inline list-separator small text-body mb-2">
            <li class="list-inline-item">Posted 7 hours ago</li>
            <li class="list-inline-item">{{ comp.address }}</li>
            <li class="list-inline-item">Full time</li>
          </ul>
        </div>
      </div>
      <!-- End Media -->
    </div>
  </div>
</div>
<!-- End Page Header -->
{% endif %}
{% endblock %}

cportal/templates/cportal/login.html
<h1>Login</h1>

cportal/templates/cportal/logout.html
<h1>Logout</h1>

cportal/templates/cportal/register.html
<!-- register.html -->

{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Register</title>
    <link rel="stylesheet" type="text/css" href="{% static 'cportal/styles.css' %}">
</head>
<body>
    <div class="form-signup">
        <h2>Register</h2>
        <form method="post">
            {% csrf_token %}
                {% for field in form %}
                    <div class="fieldWrapper">
                        {{ field.errors }}
                        {{ field.label_tag }} <br>
                        {{ field }}
                    </div>
                {% endfor %}
            <button type="submit">Register</button>
        </form>
    </div>
</body>
</html>